name: Build on Linux

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Install Dependencies
      run: |
        brew install twitchdev/twitch/twitch-cli
        sudo apt install mpv yt-dlp
        mkdir -p $HOME/.config/twitch-cli
        cp tests/resources/twitch-cli/eventCache.db tests/resources/twitch-cli/.twitch-cli.env $HOME/.config/twitch-cli/

    - name: Build Binaries
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

