name: Build on Linux with Nix

on:
  push:
    branches: [ "main", "dev", "releases/**" ]
  pull_request:
    branches: [ "main", "dev", "releases/**"]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Build
      run: nix build

